# Schedule I 한글패치 통합 설치기
# BepInEx / XUnity.AutoTranslator가 없으면 공식 저장소에서 자동 설치합니다.
$ErrorActionPreference = "Stop"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
Write-Host "==============================================" -ForegroundColor Cyan
Write-Host "   Schedule I 한글패치 설치기" -ForegroundColor Cyan
Write-Host "==============================================" -ForegroundColor Cyan

# ---------- 1) 게임 경로 찾기 (레지스트리로 Steam 위치 파악) ----------
function Get-SteamLibraries {
    $roots = New-Object System.Collections.Generic.List[string]
    foreach ($rk in @("HKCU:\Software\Valve\Steam", "HKLM:\SOFTWARE\WOW6432Node\Valve\Steam", "HKLM:\SOFTWARE\Valve\Steam")) {
        try {
            $v = Get-ItemProperty -Path $rk -ErrorAction Stop
            foreach ($name in @("SteamPath", "InstallPath")) {
                $sp = $v.$name
                if ($sp) { $roots.Add(($sp -replace '/', '\')) }
            }
        } catch {}
    }
    $roots.Add("C:\Program Files (x86)\Steam")
    $libs = New-Object System.Collections.Generic.List[string]
    foreach ($r in $roots) {
        if (-not (Test-Path $r)) { continue }
        $libs.Add($r)
        $vdf = Join-Path $r "steamapps\libraryfolders.vdf"
        if (Test-Path $vdf) {
            foreach ($m in [regex]::Matches((Get-Content $vdf -Raw), '"path"\s+"([^"]+)"')) {
                $libs.Add($m.Groups[1].Value.Replace('\\', '\'))
            }
        }
    }
    return @($libs | Select-Object -Unique)
}

$gamePath = $null
foreach ($lib in (Get-SteamLibraries)) {
    $c = Join-Path $lib "steamapps\common\Schedule I"
    if (Test-Path (Join-Path $c "Schedule I.exe")) { $gamePath = $c; break }
}
if (-not $gamePath) {
    Write-Host "게임 폴더를 자동으로 찾지 못했습니다." -ForegroundColor Yellow
    Write-Host "Steam 라이브러리에서 Schedule I 우클릭 > 관리 > 로컬 파일 보기 로 열리는 폴더의 경로를 복사해 붙여넣으세요."
    $gamePath = Read-Host "Schedule I 게임 폴더 경로"
    if ($gamePath) { $gamePath = $gamePath.Trim('"').Trim() }
    if (-not $gamePath -or -not (Test-Path (Join-Path $gamePath "Schedule I.exe"))) { Write-Host "잘못된 경로입니다." -ForegroundColor Red; pause; exit 1 }
}
Write-Host ("게임 경로: " + $gamePath) -ForegroundColor Green

if (Get-Process -Name "Schedule I" -ErrorAction SilentlyContinue) {
    Write-Host "게임이 실행 중입니다. 완전히 종료한 뒤 다시 실행해주세요." -ForegroundColor Red
    pause; exit 1
}

$tmp = Join-Path $env:TEMP "s1kr_setup"
New-Item -ItemType Directory -Force $tmp | Out-Null

# ---------- 2) BepInEx 자동 설치 ----------
if (-not (Test-Path (Join-Path $gamePath "BepInEx\core\BepInEx.Core.dll"))) {
    Write-Host "[1/4] BepInEx 다운로드 중... (공식 빌드 서버)" -ForegroundColor Cyan
    $bepUrl = "https://builds.bepinex.dev/projects/bepinex_be/733/BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.733%2B995f049.zip"
    $bepZip = Join-Path $tmp "bepinex.zip"
    Invoke-WebRequest -Uri $bepUrl -OutFile $bepZip -UseBasicParsing
    Expand-Archive $bepZip (Join-Path $tmp "bepinex") -Force
    Copy-Item (Join-Path $tmp "bepinex\*") $gamePath -Recurse -Force
    Write-Host "  BepInEx 설치 완료" -ForegroundColor Green
} else {
    Write-Host "[1/4] BepInEx 이미 설치됨 - 건너뜀" -ForegroundColor DarkGray
}

# ---------- 3) XUnity.AutoTranslator 자동 설치 ----------
$xuatDll = Join-Path $gamePath "BepInEx\plugins\XUnity.AutoTranslator\XUnity.AutoTranslator.Plugin.Core.dll"
$needXuat = $true
if (Test-Path $xuatDll) {
    $v = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($xuatDll).FileVersion
    if ($v -and ([version]$v -ge [version]"5.6.1")) { $needXuat = $false }
}
if ($needXuat) {
    Write-Host "[2/4] XUnity.AutoTranslator 5.6.1 다운로드 중... (GitHub 공식)" -ForegroundColor Cyan
    $xuUrl = "https://github.com/bbepis/XUnity.AutoTranslator/releases/download/v5.6.1/XUnity.AutoTranslator-BepInEx-IL2CPP-5.6.1.zip"
    $xuZip = Join-Path $tmp "xuat.zip"
    Invoke-WebRequest -Uri $xuUrl -OutFile $xuZip -UseBasicParsing
    Expand-Archive $xuZip (Join-Path $tmp "xuat") -Force
    Copy-Item (Join-Path $tmp "xuat\BepInEx\*") (Join-Path $gamePath "BepInEx\") -Recurse -Force
    Write-Host "  번역기 설치 완료" -ForegroundColor Green
} else {
    Write-Host "[2/4] 번역기 5.6.1+ 이미 설치됨 - 건너뜀" -ForegroundColor DarkGray
}

# ---------- 4) 번역 파일 + 보조 플러그인 ----------
Write-Host "[3/4] 한글 번역 파일 설치 중..." -ForegroundColor Cyan
$textDir = Join-Path $gamePath "BepInEx\Translation\ko\Text"
New-Item -ItemType Directory -Force $textDir | Out-Null
foreach ($f in (Get-ChildItem (Join-Path $here "payload\Text") -Filter "*.txt")) {
    Copy-Item $f.FullName (Join-Path $textDir $f.Name) -Force
}
Copy-Item (Join-Path $here "payload\KoreanTextFixer.dll") (Join-Path $gamePath "BepInEx\plugins\KoreanTextFixer.dll") -Force
$stale = Join-Path $textDir "_AutoGeneratedTranslations.txt"
if (Test-Path $stale) { Remove-Item $stale -Force }
Write-Host "  번역 58,000여 개 + 보조 플러그인 설치 완료" -ForegroundColor Green

# ---------- 5) 설정 적용 + 잠금 ----------
Write-Host "[4/4] 번역기 설정 적용 중..." -ForegroundColor Cyan
$cfgDir = Join-Path $gamePath "BepInEx\config"
New-Item -ItemType Directory -Force $cfgDir | Out-Null
$cfg = Join-Path $cfgDir "AutoTranslatorConfig.ini"
$me = "$env:USERDOMAIN\$env:USERNAME"
if (Test-Path $cfg) { & icacls "$cfg" /remove:d "$me" 2>&1 | Out-Null }
Copy-Item (Join-Path $here "payload\config\AutoTranslatorConfig.ini") $cfg -Force
& icacls "$cfg" /deny "${me}:(WD,AD,WEA,WA)" 2>&1 | Out-Null
Write-Host "  설정 적용 및 잠금 완료 (게임이 설정을 되돌리는 것 방지)" -ForegroundColor Green

# ---------- 6) 폰트 적용 여부 확인 ----------
Write-Host ""
Write-Host "----------------------------------------------" -ForegroundColor Yellow
Write-Host " 한글 폰트(을지로체)도 적용할까요?" -ForegroundColor Yellow
Write-Host ""
Write-Host " 게임 기본 폰트에는 한글이 없어서, 적용하지 않으면"
Write-Host " 번역된 글자가 네모(ㅁ)로 깨져 보일 수 있습니다."
Write-Host ""
Write-Host " * 게임 원본 파일 1개를 수정합니다 (원본은 자동 백업)"
Write-Host " * 되돌리려면: Steam > 속성 > 설치된 파일 > 파일 무결성 확인"
Write-Host "----------------------------------------------" -ForegroundColor Yellow
$ans = Read-Host " 적용하시겠습니까? [Y] 예 (권장) / [N] 아니오"
if ($ans -eq "" -or $ans -match '^[YyㅛJj]') {
    Write-Host ""
    Write-Host "[폰트] 을지로체 적용 중..." -ForegroundColor Cyan
    $fontScript = Join-Path $here "font_patch.ps1"
    if (Test-Path $fontScript) {
        & powershell -NoProfile -ExecutionPolicy Bypass -File $fontScript -NoPause -GamePath "$gamePath"
        if ($LASTEXITCODE -eq 0) { Write-Host "  폰트 적용 완료" -ForegroundColor Green }
        else { Write-Host "  폰트 적용에 실패했습니다. 나중에 '폰트적용.bat'을 실행해보세요." -ForegroundColor Yellow }
    } else {
        Write-Host "  font_patch.ps1 을 찾을 수 없습니다." -ForegroundColor Yellow
    }
} else {
    Write-Host " 폰트는 건너뜁니다. 나중에 '폰트적용.bat'으로 적용할 수 있습니다." -ForegroundColor DarkGray
}

Write-Host ""
Write-Host "==============================================" -ForegroundColor Green
Write-Host "   설치 완료! 게임을 실행하세요." -ForegroundColor Green
Write-Host "==============================================" -ForegroundColor Green
pause
